---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
library(ggplot2)
library(PubChemR)
library(rentrez)
library(xml2)
library(glue)
library(purrr)

```

```{r}

vampr <- read_tsv("/Users/sharvari/Desktop/NCBI Codeathon/antibiogram_phenotype.txt")

g <- ggplot(vampr, aes(bacteria, antibiotics, fill= phenotype)) + 
  geom_tile() + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ggtitle("VAMPr dataset")

ggsave(plot = g, filename = "/Users/sharvari/Desktop/NCBI Codeathon/VAMPr_dataset_heatmap.png", width = 15, height = 10, dpi=300)

```

```{r}

ecoli_vampr <- vampr %>% filter(bacteria == "Escherichia coli") %>% distinct(antibiotics)

for (i in 1:nrow(ecoli_vampr)) {
  print(ecoli_vampr$antibiotics[i])
  try(
    download(
      filename = ecoli_vampr$antibiotics[i],
      outformat = "json",
      path = "/Users/sharvari/Desktop/NCBI Codeathon/vampr_antibiotics_2D_compound_structures/",
      identifier = ecoli_vampr$antibiotics[i],
      namespace = "name",
      domain = "compound",
      overwrite = TRUE
    )
  )
}

# received error for "amoxicillin-clavulanic acid" so downloading that manually (re-labelling it as "augmentin")

ecoli_vampr1 <- ecoli_vampr
ecoli_vampr1$antibiotics[1] <- "augmentin"

antibiotics_df <- data.frame()
for (i in 1:nrow(ecoli_vampr1)) {
  print(ecoli_vampr1$antibiotics[i])
  result <- get_pug_rest(identifier = ecoli_vampr1$antibiotics[i], namespace = "name", domain = "compound", property = c("MolecularFormula","MolecularWeight","CanonicalSMILES"), output = "CSV")
  pubChemDataResult <- pubChemData(result)
  pubChemDataResult$antibiotics <- ecoli_vampr1$antibiotics[i]
  antibiotics_df <- rbind.data.frame(antibiotics_df, pubChemDataResult)
}

# there are multiple CIDs; keeping only the top one
length(unique(antibiotics_df$CanonicalSMILES)) # 24
length(unique(antibiotics_df$antibiotics)) #23

# getting the duplicated one
antibiotics_df %>% group_by(antibiotics, CanonicalSMILES) %>% summarise(count = n()) # cefepime has been repeated with 2 different SMILES and molecular formulas; keeping only the first one

antibiotics_df1 <- antibiotics_df[match(unique(antibiotics_df$antibiotics), antibiotics_df$antibiotics),]

antibiotics_df1$antibiotics[1] <- "amoxicillin-clavulanic acid"

ecoli_vampr2 <- vampr %>% filter(bacteria == "Escherichia coli")
ecoli_vampr2_ab <- left_join(ecoli_vampr2, antibiotics_df1)

# the first column - sample ID is actually the sample accession ID/biosample ID on NCBI
ecoli_vampr2_ab$sample_id <- paste0("SAMN0", ecoli_vampr2_ab$sample_id)

write_tsv(ecoli_vampr2_ab, "/Users/sharvari/Desktop/NCBI Codeathon/vampr_ecoli_antibiotic_smile.tsv")

```

## the plan in this section of the code is to use the biosample ID to retrieve genomic and metadata information from NCBI

## Reference: https://gist.github.com/tomsing1/ad769fa0394bf9ce04b4f786528762a5

```{r}

test <- entrez_search(db = "biosample", term = "SAMN03177615", retmax=0)
records <- xml2::read_xml(
  entrez_fetch("biosample", id = "SAMN03177615", rettype = "xml")
)

xml_data <- xml2::as_list(records)

as.data.frame(unlist(xml_data$BioSampleSet$BioSample$Description$Comment$Table$Body))
do.call(rbind.data.frame, xml_data$BioSampleSet$BioSample$Links$Link)

attr(xml_data$BioSampleSet$BioSample$Links$Link, "label")

source("/Users/sharvari/Desktop/NCBI Codeathon/BioSampleParser.R")
df_metadata <- BioSampleParser(query = "PRJNA266657")

```

